services:
  # Frontend Next.js application
  - type: web
    name: yogreek-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      echo 'NEXT_PUBLIC_API_URL="http://localhost"' > .env.production
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true

  # Product Service
  - type: web
    name: yogreek-product-service
    env: python
    plan: free
    buildCommand: |
      cd ecommerce/product_service
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd ecommerce/product_service
      python manage.py migrate
      gunicorn product_service.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 60
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: product_service.settings
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health/
    autoDeploy: true

  # User Service
  - type: web
    name: yogreek-user-service
    env: python
    plan: free
    buildCommand: |
      cd ecommerce/user_service
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd ecommerce/user_service
      python manage.py migrate
      gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 60
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: yogreek-db
    databaseName: yogreek
    plan: free 
