services:
  # Frontend Next.js application
  - type: web
    name: yogreek-frontend
    env: node
    buildCommand: |
      cd frontend
      rm -rf node_modules .next
      npm install
      npm install tailwindcss@latest postcss@latest autoprefixer@latest
      echo 'module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }' > postcss.config.js
      echo 'module.exports = { content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"], theme: { extend: {} }, plugins: [] }' > tailwind.config.js
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://yogreek-product-service.onrender.com
      - key: NEXT_PUBLIC_USER_API_URL
        value: https://yogreek-user-service.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Product Service
  - type: web
    name: yogreek-product-service
    env: python
    plan: free
    buildCommand: |
      cd ecommerce/product_service
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd ecommerce/product_service
      python manage.py migrate
      gunicorn product_service.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: product_service.settings
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: yogreek-product-service.onrender.com
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://yogreek-frontend.onrender.com
    healthCheckPath: /health/
    autoDeploy: true

  # User Service
  - type: web
    name: yogreek-user-service
    env: python
    plan: free
    buildCommand: cd ecommerce/user_service && pip install -r requirements.txt
    startCommand: cd ecommerce/user_service && python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: yogreek-user-service.onrender.com
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://yogreek-frontend.onrender.com
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: yogreek-db
    databaseName: yogreek_db
    user: yogreek
    plan: free 
