services:
  # Frontend Next.js application
  - type: web
    name: yogreek-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://yogreek-product-service.onrender.com
      - key: NEXT_PUBLIC_USER_API_URL
        value: https://yogreek-user-service.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Product Service
  - type: web
    name: yogreek-product-service
    env: python
    plan: free
    buildCommand: |
      cd ecommerce/product_service
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd ecommerce/product_service
      gunicorn product_service.wsgi:application --workers 1 --threads 8
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: product_service.settings
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://yogreek-frontend.onrender.com
    healthCheckPath: /api/health/
    autoDeploy: true

  # User Service
  - type: web
    name: yogreek-user-service
    env: python
    plan: free
    buildCommand: |
      cd ecommerce/user_service
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd ecommerce/user_service
      gunicorn config.wsgi:application --workers 1 --threads 8
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://yogreek-frontend.onrender.com
    healthCheckPath: /api/health/
    autoDeploy: true

databases:
  - name: yogreek-db
    databaseName: yogreek
    plan: free 
